In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# loading dataset

In [19]:
df = pd.read_csv("HR.csv")

In [20]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7

# EDA

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               1470 non-null   int64
 1   Attrition         1470 non-null   str
 2   BusinessTravel    1470 non-null   str
 3   DailyRate         1470 non-null   int64
 4   Department        1470 non-null   str
 5   DistanceFromHome  1470 non-null   int64
 6   Education         1470 non-null   int64
 7   EducationField    1470 non-null   str
 8   EmployeeCount     1470 non-null   int64
 9   EmployeeNumber    1470 non-null   int64
dtypes: int64(6), str(4)
memory usage: 176.2 KB

In [22]:
df.isnull().sum()

Age                 0
Attrition           0
BusinessTravel      0
DailyRate           0
Department          0
DistanceFromHome    0
Education           0
EducationField      0
EmployeeCount       0
EmployeeNumber      0
dtype: int64

In [23]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber'],
      dtype='str')

In [33]:
df.drop(columns = ["EmployeeCount"] , inplace = True)

# Outliers Detection

In [26]:
q3 = df['Age'].quantile(0.75)
q1 = df['Age'].quantile(0.25)
iqr = q3 - q1

In [27]:
high = q3 + 1.5 * iqr
low = q1 - 1.5 * iqr

In [28]:
# Outliers
df[(df['Age'] > high) | (df['Age'] < low)]
#NO OUTLIER PRESENT

Empty DataFrame
Columns: [Age, Attrition, BusinessTravel, DailyRate, Department, DistanceFromHome, Education, EducationField, EmployeeCount, EmployeeNumber]
Index: []

In [29]:
df['Attrition'].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

## Loading Dataset in SQL

In [30]:
import mysql.connector
import pandas as pd
from sqlalchemy import create_engine

conn = mysql.connector.connect(
    host = "localhost",user = "root" , password = "Manan274545", database = "hr_db")
cursor = conn.cursor()

In [31]:
from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://root:Manan274545@localhost/hr_db")

df.to_sql("hr", con=engine, if_exists="replace", index=False)

1470

### converting cleaned dataset into CSV

In [32]:
df.to_csv("hr_new.csv" , index = False)